{
 "title": "Data Drift and Prediction Issues Dashboard",
 "description": "This dashboard will be used by ML engineers and data scientist to detect ML model or application issues",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prediction Frequency Histogram",
   "type": "histogram",
   "description": "A histogram of the number of predictions made in the last 10 minutes, helping detect unusual spikes in prediction frequency.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('minute', created_at) AS time, \r\n    COUNT(*) AS prediction_count \r\nFROM \r\n    predictions \r\n\r\nGROUP BY \r\n    time \r\nORDER BY \r\n    time;"
    }
   ]
  },
  {
   "title": "Data Drift Detection: Age Comparison Between Training and Serving",
   "type": "timeseries",
   "description": "A line graph that compares the average age from recent predictions with the average age in the training set.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('minute', p.created_at) AS time, \r\n    AVG(f.age) AS avg_age_serving \r\nFROM \r\n    predictions p \r\n    JOIN features f ON p.id = f.id \r\n\r\nGROUP BY \r\n    time \r\nORDER BY \r\n    time;"
    }
   ]
  },
  {
   "title": "Line Graph: Average Prediction Values",
   "type": "timeseries",
   "description": " A line graph that shows the average prediction output value over the expected time interval.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    DATE_TRUNC('minute', created_at) AS time, \r\n    AVG(prediction) AS avg_prediction \r\nFROM \r\n    predictions \r\n\r\nGROUP BY \r\n    DATE_TRUNC('minute', created_at) \r\nORDER BY \r\n    time;\t"
    }
   ]
  },
  {
   "title": "Histogram: Predicted Classes",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    prediction AS predicted_class, \r\n    COUNT(*) AS count \r\nFROM \r\n    predictions \r\n    \r\nGROUP BY \r\n    prediction \r\nORDER BY \r\n    prediction;"
    }
   ]
  }
 ]
}