{
 "title": "Ingested data monitoring dashboard",
 "time": { "from": "2024-11-07T20:22:00.000Z", "to": "2024-11-08T09:38:00.000Z" },
 "panels": [
  {
   "title": " Histogram: Invalid Data Percentage",
   "type": "histogram",
   "description": "A histogram showing the distribution of invalid data percentages across different ingestions ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ROUND(invalid_percentage) AS invalid_data_percentage, \r\n    COUNT(*) AS frequency \r\nFROM \r\n    data_statistics \r\nGROUP BY \r\n    ROUND(invalid_percentage) \r\nORDER BY \r\n    invalid_data_percentage;\t"
    }
   ]
  },
  {
   "title": "Line Graph of File Processing Rate",
   "type": "timeseries",
   "description": "shows the number of files processed over time, to track changes in ingestion volume.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    timestamp AS time, \r\n    COUNT(file_name) AS files_processed \r\nFROM \r\n    data_statistics \r\nGROUP BY \r\n    timestamp \r\nORDER BY \r\n    timestamp;"
    }
   ]
  },
  {
   "title": "Bar Chart: Number of Detected Data Problems Per Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    timestamp AS time, \r\n    COUNT(*) FILTER (WHERE invalid_columns IS NOT NULL AND invalid_columns <> '') AS missing_values,\r\n    COUNT(*) FILTER (WHERE validation_success = FALSE) AS failed_validations\r\nFROM \r\n    data_statistics \r\nGROUP BY \r\n    timestamp \r\nORDER BY \r\n    timestamp DESC;"
    }
   ]
  },
  {
   "title": "Bar Chart: Percentage of Valid vs. Invalid Data Samples",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  timestamp AS time, \r\n  valid_records * 100.0 / total_records AS valid_percentage,\r\n  invalid_records * 100.0 / total_records AS invalid_percentage\r\nFROM data_statistics\r\nORDER BY time;"
    }
   ]
  }
 ]
}